### PR TITLE
Update Snap Kit on Android to v2.1.0

### LINKED ISSUE #40: Build / sharing does not work targeting Android 31+
When following the [Android installation guide](https://github.com/TimmyRB/snapkit/wiki/Android-Installation) and running on a Pixel 6, the following installation error is thrown:

```
adb: failed to install app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during
installPackageLI: /data/app/vmdl1231205057.tmp/base.apk (at Binary XML file line #68): com.snapchat.kit.sdk.SnapKitActivity: Targeting S+ (version 31 and above) requires that an explicit value for
android:exported be defined when intent filters are present]
```

After adding `android:exported="false"` to the activity, the following error is thrown during runtime:

```
Unhandled Exception: PlatformException(error, fun.gatch.story_sharing_example: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
```

## Workaround

A workaround I was able to use was downgarding the `targetSdkVersion` to `30` in `app/build.gradle`:

```gradle
...
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
...
```

### PR DESCRIPTION
**Pull request by JonasWanke**
Closes: #40

The main change is that the native Android implementation now uses [Snap Kit 2.1.0](https://docs.snap.com/snap-kit/changelog#version-210-1) instead of version 1.10.0. This is a **breaking change** because the meta-data tags in `AndroidManifest.xml` now use different names. The Creative Kit in the provided example app works fine (after modifying the Android application ID and Snapchat client ID), but logging in didn't work for me. I only get a generic error dialog stating that an error occurred: “Something went wrong. Please try again.” Maybe you have an idea of why this isn't working?

I added a changelog entry with a guide for users of this plugin. In addition, the wiki has to be updated:

- https://github.com/TimmyRB/snapkit/wiki/Installation-Overview
  - update snapkit version to 3.0.0
- https://github.com/TimmyRB/snapkit/wiki/Android-Installation
  - steps 2, 3: remove
  - step 4: apply the migration guide

BTW, I'd recommend changing the changelog's order from most recent to least recent, as that's far more common and users are likely most interested in the newer releases.

Additionally, I widened support for the http package since it recently had a new major release. The Dart code only contains minor modifications that made the code easier to read for me.

### CODE REVIEW

**Comment by William-McGonagle** [comment]
@JonasWanke @TimmyRB 
Is there anything I can do to help contribute? I am working on a Snapkit app and need a bunch of features.

**Comment by simplenotezy** [comment]
Hey @JonasWanke thanks for the PR. We've tried implementing it in our project (especially due to your http upgrade). However, doing androi build, fails with:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseAarMetadata'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.snapchat.kit.sdk:creative:1.13.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/snapchat/kit/sdk/creative/1.13.0/creative-1.13.0.pom
       - https://jcenter.bintray.com/com/snapchat/kit/sdk/creative/1.13.0/creative-1.13.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/snapchat/kit/sdk/creative/1.13.0/creative-1.13.0.pom
       - https://repo.maven.apache.org/maven2/com/snapchat/kit/sdk/creative/1.13.0/creative-1.13.0.pom
       - https://www.jitpack.io/com/snapchat/kit/sdk/creative/1.13.0/creative-1.13.0.pom
     Required by:
         project :app
   > Could not find com.snapchat.kit.sdk:login:1.13.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/snapchat/kit/sdk/login/1.13.0/login-1.13.0.pom
       - https://jcenter.bintray.com/com/snapchat/kit/sdk/login/1.13.0/login-1.13.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/snapchat/kit/sdk/login/1.13.0/login-1.13.0.pom
       - https://repo.maven.apache.org/maven2/com/snapchat/kit/sdk/login/1.13.0/login-1.13.0.pom
       - https://www.jitpack.io/com/snapchat/kit/sdk/login/1.13.0/login-1.13.0.pom
     Required by:
         project :app
   > Could not find com.snapchat.kit.sdk:bitmoji:1.13.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/snapchat/kit/sdk/bitmoji/1.13.0/bitmoji-1.13.0.pom
       - https://jcenter.bintray.com/com/snapchat/kit/sdk/bitmoji/1.13.0/bitmoji-1.13.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/snapchat/kit/sdk/bitmoji/1.13.0/bitmoji-1.13.0.pom
       - https://repo.maven.apache.org/maven2/com/snapchat/kit/sdk/bitmoji/1.13.0/bitmoji-1.13.0.pom
       - https://www.jitpack.io/com/snapchat/kit/sdk/bitmoji/1.13.0/bitmoji-1.13.0.pom
     Required by:
         project :app
   > Could not find com.snapchat.kit.sdk:core:1.13.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/snapchat/kit/sdk/core/1.13.0/core-1.13.0.pom
       - https://jcenter.bintray.com/com/snapchat/kit/sdk/core/1.13.0/core-1.13.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/snapchat/kit/sdk/core/1.13.0/core-1.13.0.pom
       - https://repo.maven.apache.org/maven2/com/snapchat/kit/sdk/core/1.13.0/core-1.13.0.pom
       - https://www.jitpack.io/com/snapchat/kit/sdk/core/1.13.0/core-1.13.0.pom
     Required by:
         project :app

**Comment by JonasWanke** [comment]
@simplenotezy That sounds like these four dependencies are still inside your module-level `build.gradle` file (`android/app/build.gradle`). Can you try removing them? With this PR, you no longer need to add native Android dependencies, and this package only adds dependencies on the newer versions `com.snap.creativekit:creativekit:2.1.0` and `com.snap.loginkit:loginkit:2.1.0`

**Comment by simplenotezy** [comment]
> @simplenotezy That sounds like these four dependencies are still inside your module-level `build.gradle` file (`android/app/build.gradle`). Can you try removing them? With this PR, you no longer need to add native Android dependencies, and this package only adds dependencies on the newer versions `com.snap.creativekit:creativekit:2.1.0` and `com.snap.loginkit:loginkit:2.1.0`

You were right, missed that. Thanks!

**Comment by simplenotezy** [comment]
By the way, not sure if you are using the "share link" functionality @JonasWanke - but did you notice that Snapchat silently removed support for this from day-to-day a few months back? All of a sudden our embedded links in shared posts wouldn't work and I noticed the same happened to bigger players such as BeReal and other apps using that feature.

**Comment by JonasWanke** [comment]
@simplenotezy No, I mostly focused on the Snapchat installation check and basic media sharing, which are the only things we're currently using

**Comment by coolpistachio** [comment]
@JonasWanke @TimmyRB are there any plans to review/merge this PR? It would make things a lot easier for folks that want to keep using this library for Snapchat integration.

**Comment by TimmyRB** [comment]
Hi @JonasWanke, thanks for the great work! I'm currently in the process recreating this package since so much has changed with both Flutter and the SnapSDK since I first created this plugin. I've merged your changes into `snapkit-refresh-and-fixes` which will be the 3.0.0 release of this plugin using SnapSDK 2.5.0 on iOS and 2.1.0 on Android. I've completed the iOS side of things and am now moving onto Android where I plan to migrate both my code and your new code from Java to Kotlin. 

If you'd like to test out the new version before it releases, you can do so like this in your project's `pubspec.yaml`
```yaml
snapkit:
       git:
         url: git://github.com/TimmyRB/snapkit.git
         ref: snapkit-refresh-and-fixes
```
Though it only contains new iOS and Dart code at this moment, I will update this comment when that changes.

I have created PR #50 to track progress

**Comment by TimmyRB** [comment]
Quick update: I have updated the native Android side of things and the CreativeKit works great and adds sharing with video back to Android, however LoginKit isn't working at the moment for some unknown reason, I'm looking into it at the moment but Snapchat's error messages aren't exactly the most descriptive.

**Pull request closed without merging**
